# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'chocofi'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right", "settings_reset"]'
      #kconfig: '["CONFIG_ZMK_DISPLAY=y"]\n[snippet: zmk-usb-logging]'
      kconfig: '["CONFIG_ZMK_SLEEP=n\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_IDLE_TIMEOUT=30000"]\n[snippet: zmk-usb-logging]'      
